version: '3.8'

services:
    app:
        build: .
        container_name: minecraft-sandbox
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        user: "${UID}:${GID}"
        depends_on:
            - db
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - app-network

    nginx:
        image: nginx:1.23
        container_name: minecraft-sandbox-nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        environment:
            - SERVER_NAME=${APP_URL}
        networks:
            - app-network

    vite:
        image: node:20
        container_name: minecraft-sandbox-vite
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "${VITE_PORT}:${VITE_PORT}"
        command: [ "npm", "run", "dev" ]
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: minecraft-sandbox-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
